# Generated by Django 2.2.7 on 2019-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='apellido')),
                ('address', models.CharField(max_length=100, verbose_name='dirección')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción del Pago')),
                ('amount', models.IntegerField(verbose_name='monto del pago')),
                ('type_of_payment', models.CharField(max_length=50, verbose_name='tipo de pago')),
                ('proof_of_payment', models.ImageField(upload_to='payments')),
                ('date_of_payment', models.DateTimeField(verbose_name='fecha de pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-date_of_payment'],
            },
        ),
    ]
