# Generated by Django 2.2.7 on 2019-11-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191125_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='proof_of_payment',
            field=models.ImageField(upload_to='payments', verbose_name='Comprobante de Pago'),
        ),
    ]
