# Generated by Django 2.2.7 on 2019-12-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20191127_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='monto'),
        ),
    ]
