# Generated by Django 2.2.7 on 2019-12-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20191209_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='proof_of_payment',
            field=models.FileField(null=True, upload_to='payments', verbose_name='Comprobante de Pago'),
        ),
    ]
