# Generated by Django 2.2.7 on 2019-12-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20191209_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='proof_of_payment',
            field=models.ImageField(upload_to='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>', verbose_name='Comprobante de Pago'),
        ),
    ]
