# Generated by Django 2.2.7 on 2019-12-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20191209_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='proof_of_payment',
            field=models.ImageField(upload_to='payments/<django.db.models.fields.CharField>_<django.db.models.fields.CharField>/', verbose_name='Comprobante de Pago'),
        ),
    ]
