# Generated by Django 2.2.7 on 2019-12-10 20:24

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20191209_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='proof_of_payment',
            field=models.ImageField(upload_to=payments.models.custom_upload_to, verbose_name='Comprobante de Pago'),
        ),
    ]
