# Generated by Django 2.2.7 on 2019-11-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='registered',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de registro'),
        ),
    ]
