# Generated by Django 2.2.7 on 2019-11-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20191125_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro'),
        ),
    ]
