# Generated by Django 2.2.7 on 2019-12-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='monto'),
        ),
    ]
