# Generated by Django 2.2.7 on 2019-11-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_auto_20191124_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='número telefónico del propietario'),
        ),
        migrations.AddField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='número telefónico'),
        ),
    ]
