# Generated by Django 2.2.7 on 2019-12-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_auto_20191127_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='type_of_property',
            field=models.CharField(choices=[('1', 'Casa'), ('2', 'Departamento'), ('3', 'Lote Baldío')], max_length=1),
        ),
    ]
