# Generated by Django 2.2.7 on 2019-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_auto_20191206_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='type_of_property',
            field=models.CharField(max_length=50, verbose_name='tipo de inmueble'),
        ),
    ]
